name: mental_health
description: "Mental health is a state of well-being in which every individual realizes his or her own potential, can cope with the normal stresses of life, can work productively and fruitfully, and is able to make a contribution to her or his community."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: 6.1.0
  flutter_bloc: ^8.1.6
  audio_video_progress_bar: ^2.0.3
  http: ^1.2.2
  just_audio: ^0.9.40
  get_it: ^8.0.0

  # Firebase dependencies
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4

  # Lottie animations
  lottie: ^3.1.2
  flutter_svg: ^2.2.0
  sensors_plus: ^6.1.1

  # Additional dependencies for professional tasks
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.1
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  translator: ^1.0.0
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  sqflite: ^2.4.2
  path: ^1.8.3
  intl: ^0.20.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/sf/
    - assets/icons/
    - assets/datas/tasks/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
